# Jekyll configuration

name: DMS Jawara eGov
description: DMS Jawara eGov

# url is currently only used only for the RSS feed in feed.xml
url: https://developerbanten.github.io/dokumentasi-banten2018/

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ""

# These can be '' to hide the Github or Gitlab nav buttons
github: 'scotte/jekyll-clean'
gitlab: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
collections:
  my_collection:
    output: true
  ehibahbansos:
    output: true
    permalink: /:collection/:name:output_ext
  jawara_egov:
    output: true
    permalink: /:collection/:name:output_ext
  dashboard_pimpinan:
    output: true
    permalink: /:collection/:name:output_ext
  sop_online:
    output: true
    permalink: /:collection/:name:output_ext
  yankes:
    output: true
    permalink: /:collection/:name:output_ext
  sso:
    output: true
    permalink: /:collection/:name:output_ext
  simbada:
    output: true
    permalink: /:collection/:name:output_ext